# Generated by Django 5.0.7 on 2024-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_webhook', '0005_webhook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooktopic',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='The permissions a user must have on an object to receive the webhook', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='webhooktopic',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
