# Generated by Django 5.0.7 on 2024-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_webhook', '0006_webhooktopic_permissions_alter_webhooktopic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktopic',
            name='permissions',
        ),
        migrations.AddField(
            model_name='webhooktopic',
            name='permissions_required',
            field=models.ManyToManyField(blank=True, help_text='The permissions a user must have on an object to receive the webhook', to='auth.permission'),
        ),
    ]
